### ISSUE TITLE
Buffers are stored with 0-length in header

### ISSUE THREAD

**Issue by oliversalzburg** [petersirka/node-filestorage#14]
When storing a buffer, the length will always be 0, which is obviously an issue when reading the data back.

```js
var storage = require('filestorage').create();
var id = storage.insert('file.txt', new Buffer('hello world', 'utf-8'), null, function(err, id, stat) {
  console.log(stat);
  
  storage.stat(id, function(err,stat) {
    console.log(stat);
  });
});
```

```shell
$ node test.js
{ name: 'file.txt',
  extension: 'txt',
  type: 'text/plain',
  width: 0,
  height: 0,
  length: 0,
  custom: null,
  stamp: 1446465718626 }
{ name: 'file.txt',
  extension: 'txt',
  type: 'text/plain',
  width: 0,
  height: 0,
  length: 0,
  custom: null,
  stamp: 1446465718626 }
```

**Comment by oliversalzburg** [comment]
To work around this issue, one can wrap the buffer in a stream:
```js
var stream = require( "stream" );
var bufferStream = new stream.PassThrough();
bufferStream.end( buffer );
```

**Comment by petersirka** [comment]
Hi @oliversalzburg,
I'll check it today.

Thanks!

**Comment by oliversalzburg** [comment]
That'd be awesome :)

When I was debugging, I ended up at https://github.com/petersirka/node-filestorage/blob/master/index.js#L185. `stats.size` here refers to the `stats` object relating to the temporary file, which is still at 0. I hope that's helpful to you.

Cheers

**Comment by petersirka** [comment]
I have fixed the problem with length. You can test it.
Thanks! I'll publish it today into the NPM.

**Comment by oliversalzburg** [comment]
Yep. Seems to work great. Thanks a lot for the quick fix :+1:

**Comment by petersirka** [comment]
I have published a new version into the NPM.
Thanks.
