### ISSUE TITLE
storage.insert is not a function

### ISSUE THREAD

**Issue by cfirs** [petersirka/node-filestorage#23]
hi, i try to use the basic function insert,
this is my code:

import storage = require('filestorage');
storage.create('j:st');
storage.insert('a.txt', 'j:750M/a.txt','my custom data', function(err, id, stat) {
    console.log(id);
    console.log(stat);

    // stat.name        - file name
    // stat.extension   - file extension
    // stat.length      - file length
    // stat.type        - content type
    // stat.width       - picture width
    // stat.height      - picture height
    // stat.custom      - your custom value
    // stat.stamp       - date created ticks, new Date(stat.stamp)

}, 'new logo');

what i am doing worng?

**Comment by petersirka** [comment]
```javascript
var mystorage = storage.create('j:st');
mystorage.insert('a.txt', 'j:750M/a.txt','my custom data', function(err, id, stat) {
});
```

**Comment by cfirs** [comment]
tnx, but now he look for callback' but i give him....

[DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

**Comment by petersirka** [comment]
Try to use latest beta `npm install filestorage@beta`.

**Comment by petersirka** [comment]
I'll publish it today.
