### ISSUE TITLE
storage.pipe hangs in version 1.7.0

### ISSUE THREAD

**Issue by kissgab** [petersirka/node-filestorage#24]
After updating the package from 1.5.0 to 1.7.0 requests to serve images / files stopped working.
After some debug it turned out that the storage.pipe() hangs.
In the v1.7.0 source code I found this line: 
`self.$events.pipe && self.emit('pipe', id, stat, Fs.createReadStream(filename, options).pipe(res));`
In my case the `self.$events.pipe` is undefined so the `Fs.createReadStream(filename, options).pipe(res)` does not get called so the request does not end.

**Comment by petersirka** [comment]
Hi @kissgab, try to use `beta` version. I have fixed it.

```bash
$ npm install filestorage@beta
```

Let me know.

**Comment by kissgab** [comment]
I tried this:
`kissgab@vps1:~/test$ npm install filestorage@beta
test@1.0.0 /home/kissgab/test
└── filestorage@1.7.1-1 

kissgab@vps1:~/test$ cat node_modules/filestorage/index.js | grep "self\.\$events\.pipe"

self.$events.pipe && self.emit('pipe', id, stat, reader, req);
self.$events.pipe && self.emit('pipe', id, stat, Fs.createReadStream(filename, options).pipe(res));`

The `self.$events.pipe && self.emit` condition still exists.

**Comment by petersirka** [comment]
Yes :-( ... I have fixed it now. Sorry.

**Comment by kissgab** [comment]
Thanks, it works perfectly! :)

**Comment by YomaDan** [comment]
If use with express, and pass response from express as pipe to out, throw error:

TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Expires"]
    at validateHeader (_http_outgoing.js:506:11)
    at ServerResponse.setHeader (_http_outgoing.js:510:3)
    at ServerResponse.setWriteHeadHeaders (F:\cmen_crewing\node_modules\on-headers\index.js:82:19)
    at ServerResponse.writeHead (F:\cmen_crewing\node_modules\on-headers\index.js:41:36)
    at F:\cmen_crewing\node_modules\filestorage\index.js:875:7
    at ReadStream.<anonymous> (F:\cmen_crewing\node_modules\filestorage\index.js:562:4)
    at Object.onceWrapper (events.js:272:13)
    at ReadStream.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)

Comment "Expires" in sets of headers works fine. Please fix this bug.

**Comment by petersirka** [comment]
Hi, try it:

```bash
$ npm install filestorage
```

**Comment by YomaDan** [comment]
'Expires': expires.toUTCString(),
Good work. Thanks.

**Comment by YomaDan** [comment]
Cache works fine, good solution for store files

**Comment by petersirka** [comment]
Great!
