### ISSUE TITLE
utils.dimensionJPG(chunk); returns undefined sometimes

### ISSUE THREAD

**Issue by davidworkman9** [petersirka/node-filestorage#9]
In this block of code:
https://github.com/petersirka/node-filestorage/blob/master/index.js#L368-L373

```
size = utils.dimensionJPG(chunk);
if (size === null)
  return;
header.width = size.width;
```

 There is a check if size is null, but I ran into a case where it returned undefined. The check should be that size is an object I think.

**Comment by petersirka** [comment]
Hi @davidworkman9,
thanks ... can you create a small example with this problem? (please create a new issue).
